gamereviews/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
]

gamereviews/gamereviews/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls'))
]

gamereviews/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('game/<int:id>/', views.detail, name='detail'),
    path('addgame/', views.add_game, name='add_game'),
    path('editgame/<int:id>/', views.edit_game, name='edit_game'),
    path('deletegame/<int:id>/', views.delete_game, name='delete_game'),
    path('addreview/<int:id>/', views.add_review, name='add_review'),
    path('editreview/<int:id_game>/<int:id_review>/', views.edit_review, name='edit_review'),
    path('deletereview/<int:id_game>/<int:id_review>/', views.delete_review, name='delete_review'),
    path('profile/', views.my_profile, name='my_profile')
]

gamereviews/main/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User

# Create your models here.
class Game(models.Model):
    name = models.CharField(max_length=50)
    release_year = models.IntegerField(validators=[MinValueValidator(1950), MaxValueValidator(2020)])
    company = models.CharField(max_length=20)
    description = models.TextField(max_length=512)
    avg_rating = models.FloatField(default=0)
    image = models.URLField(default=None)

    def __str__(self):
        return self.name

class Review(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=1024)
    rating = models.FloatField(default=0, validators=[MinValueValidator(0), MaxValueValidator(10)])

    def __str__(self):
        return self.user.username

    def get_game(self):
        return self.game

gamereviews/main/forms.py
from django import forms
from .models import *

# Forma za dodavanje igrice
class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'release_year', 'company', 'description', 'image']

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['comment', 'rating']

gamereviews/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import *
from .forms import *
from django.db.models import Avg

# Create your views here.
def home(request):
    query = request.GET.get('name')
    allGames = None
    if query:
        allGames = Game.objects.filter(name__icontains=query)
    else:
        allGames = Game.objects.all()
    return render(request, 'main/index.html', { 'games': allGames })

def detail(request, id):
    game = get_object_or_404(Game, pk=id)
    reviews = Review.objects.filter(game=id)

    if reviews:
        average = reviews.aggregate(Avg('rating'))['rating__avg']
        average = round(average, 1)

        game.avg_rating = average
        game.save()

    return render(request, 'main/details.html', { 'game': game, 'reviews': reviews })


# Dodavanje igrice u bazu
def add_game(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            if request.method == 'POST':
                form = GameForm(request.POST or None)

                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect('main:home')
            else:
                form = GameForm()
            return render(request, 'main/addgame.html', { 'form': form, 'controller': 'Add game' })
        else:
            # return redirect('main:home')
            return render(request, 'main/index.html', {'error': 1, 'games': Game.objects.all() })
    return redirect('accounts:login_user')


# Azuriranje postojece igrice u bazi
def edit_game(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            game = get_object_or_404(Game, pk=id)

            if request.method == "POST":
                form = GameForm(request.POST or None, instance=game)

                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect('main:detail', id)
            else:
                form = GameForm(instance=game)
            return render(request, 'main/addgame.html', {'form': form, 'controller': 'Edit game' })
        else:
            return redirect('main:home')
    return redirect('accounts:logins')

# Brisanje igrice iz baze
def delete_game(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            game = get_object_or_404(Game, pk=id)

            game.delete()
            return redirect('main:home')
        else:
            return redirect('main:home')
    return redirect('accounts:logins')


def add_review(request, id):
    if request.user.is_authenticated:
        game = Game.objects.get(pk=id)

        if request.method == 'POST':
            form = ReviewForm(request.POST or None)

            if form.is_valid():
                data = form.save(commit=False)
                data.comment = request.POST['comment']
                data.rating = request.POST['rating']
                data.user = request.user
                data.game = game
                data.save()
                return redirect('main:detail', id)
        else:
            form = ReviewForm()
        return render(request, 'main/details.html', { 'form': form })
    else:
        return redirect('accounts:login_user')


def edit_review(request, id_game, id_review):
    if request.user.is_authenticated:
        game = Game.objects.get(pk=id_game)
        review = Review.objects.get(game=game, id=id_review)

        if request.user == review.user or request.user.is_superuser:
            if request.method == 'POST':
                form = ReviewForm(request.POST, instance=review)

                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect('main:detail', id_game)
            else:
                form = ReviewForm(instance=review)
            return render(request, 'main/editreview.html', { 'form': form })
        else:
            return redirect('main:details', id_game)
    else:
        return redirect('accounts:login_user')

def delete_review(request, id_game, id_review):
    if request.user.is_authenticated:
        game = Game.objects.get(id=id_game)
        review = Review.objects.get(game=game, id=id_review)

        if request.user == review.user or request.user.is_superuser:
            review.delete()
        return redirect('main:detail', id_game)
    else:
        return redirect('accounts:login_user')

def my_profile(request):
    if request.user.is_authenticated:
        user_profile = User.objects.get(pk=request.user.id)
        reviews = Review.objects.filter(user=user_profile)

        return render(request, 'main/profile.html', { 'user_profile': user_profile, 'reviews': reviews })
    else:
        return redirect('accounts:login_user')

gamereviews/main/templates/main/addgame.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<br>
<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">{{ controller }}:</h3>
            <form action="" method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <br>
                <input type="submit" value="{{ controller }}">
            </form>
        </div>
    </div>
</div>

{% endblock %}

gamereviews/main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>Game reviews</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:home' %}">Game Reviews</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'main:add_game' %}">Add a game</a>

            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a href="{% url 'accounts:login_user' %}" class="dropdown-item">My Profile</a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'accounts:logout_user' %}" class="dropdown-item">Logout</a>
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a href="{% url 'accounts:login_user' %}" class="nav-link">Login</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'accounts:register' %}" class="nav-link">Register</a>
            </li>
            {% endif %}
        </ul>
        <form class="d-flex" method="GET">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="name">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        </div>
    </div>
    </nav>

    {% block content %}


    {% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

gamereviews/main/templates/main/details.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <br>
    <div class="card">
        <div class="card-body">
        <div class="row">
            <div class="col-md-3">
                <div class="text-center">
                    <h2>{{ game.name }}</h2>
                    <img src="{{ game.image }}" alt="" class="img-fluid" width="75%">
                </div>
            </div>
            <div class="col-md-8">
                <h5>{{ game.description }}</h5>
                <br>
                <h4><strong>{{ game.company }} - <i>{{ game.release_year }}</i></strong></h4>
                <h5>Average Rating: {{ game.avg_rating }}/10</h5>
                {% if request.user.is_authenticated and request.user.is_superuser %}
                <a href="{% url 'main:edit_game' game.id %}" class="btn btn-warning">Edit game</a>
                <a href="{% url 'main:delete_game' game.id %}" class="btn btn-danger">Delete game</a>
                {% endif %}
            </div>
        </div>
    </div>
    </div>
    <br>
    {% if request.user.is_authenticated %}
    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Reviews:</h3>
            <form action="{% url 'main:add_review' game.id %}" method="POST">
                {% csrf_token %}
                <label for="comment">Review:</label>
                <textarea name="comment" required id="comment" cols="30" rows=5 class="form-control"></textarea>

                <label for="rating">Rating:</label>
                <input type="number" min="0" max="10" step="0.1" name="rating" id="rating" class="form-control">

                <br>
                <input type="submit" class="btn btn-danger" value="Add Review">
            </form>
        </div>
    </div>
    {% else %}
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">You need to login to add a review.</h3>
        </div>
    </div>
    {% endif %}
    <br>
    <div class="card">
        <div class="card-body" style="background-color: #757272">
            <h3 class="text-center">Reviews:</h3>
            <br>
            {% for review in reviews %}
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3">
                                <h5 class="text-left">{{ review.user.username }}</h5>
                                <h5>{{ review.rating }}</h5>
                                {% if request.user == review.user or request.user.is_superuser %}
                                    <a href="{% url 'main:edit_review' game.id review.id %}">Edit</a>
                                    <a href="{% url 'main:delete_review' game.id review.id %}" onclick="return confirm('Are you sure you want to delete this review?');">Delete</a>
                                {% endif %}
                            </div>
                            <div class="col-md-9">
                                <p>{{ review.comment }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

gamereviews/main/templates/main/editreview.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<br>
<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Edit Review:</h3>
            <form action="" method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <br>
                <input type="submit" value="Edit Review" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

gamereviews/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<br>
{% if error %}
<div class="container">
    <div class="alert alert-danger" role="alert">
        You need to have admin permissions to add games.
    </div>
</div>
{% endif %}
<br>
<div class="container">
    <div class="card">
        <div class="body">
            <div class="row">
                {% for game in games %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center"><img src="{{ game.image }}" alt="" class="img-fluid"></div>
                            
                            <h4 class="text-center">{{ game.name }}</h4>
                            <div class="text-center">
                                <strong>{{ game.company }}</strong>
                                <br>
                                <i>{{ game.release_year }}</i>
                            </div>
                            <a href="{% url 'main:detail' game.id %}">More info</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

gamereviews/main/templates/main/profile.html
{% extends 'main/base.html' %}

{% block content %}

<br>
<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <h1 class="text-center">{{ user_profile.username }}</h1>
                    <h3 class="text-center">{{ user_profile.first_name }} {{ user_profile.last_name }}</h3>
                </div>
                <div class="col-md-5">
                    <h2 class="text-center">All User Reviews:</h2>
                    <br>
                    {% for review in reviews %}
                    <div class="card">
                        <div class="card-body">
                            <div class="class-md-4">
                                <h4><a href="{% url 'main:detail' review.get_game.id %}">{{ review.get_game.name }}</a></h4>
                                <p>{{ review.comment }}</p>
                            </div>
                        </div>
                    </div>
                    <br>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}